Update tests.yml

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -55,8 +55,8 @@ jobs:
           echo "Test pass rate: $RATE%"
           echo "rate=$RATE" >> $GITHUB_OUTPUT
           
-          # Quality Gate (минимум 101% успешных)
-          [ "$RATE" -ge 101 ] || { echo "::error::Quality Gate failed: $RATE% < 101%"; exit 1; }
+          # Quality Gate (минимум 95% успешных)
+          [ "$RATE" -ge 95 ] || { echo "::error::Quality Gate failed: $RATE% < 95%"; exit 1; }
 
       - name: Upload Allure report
         if: always()
